# spring configuration
spring:
   application:
      name: mysite
   
   #aop
   aop:
      auto: true
      proxy:-target-class: true
      
   # devtools 
   devtools:
      livereload:
         enabled: true
   
   #mvc   
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
   
   # data Source
   datsource:
      drive-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.197:3306/webdb?charset=utf8
      username: webdb
      passoword: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

#
mybatis:
   config-location: classpath:mybatis/configuration.xml
      
# server configuration
server:
   port: 8080
   servlet:
      context-path: /mysite6
      encoding:
         charset: utf-8
         enabled: true

# logging
logging:
   config: classpath:logback.xml    